const translations = {
  id: {
    navLabel: 'Navigasi utama',
    navHome: 'BERANDA',
    navCameras: 'KAMERA',
    navPrice: 'HARGA',
    navResults: 'HASIL FOTO',
    navRules: 'ATURAN',
    navAbout: 'TENTANG',
    navContact: 'KONTAK',
    brandHome: 'Beranda clicknclipcams',
    languageLabel: 'Pilihan bahasa',
    languageIndonesian: 'Bahasa Indonesia',
    languageEnglish: 'Bahasa Inggris',
    booking: 'PESAN SEKARANG ↗',
    menuOpen: 'Buka menu',
    menuClose: 'Tutup menu',
    copyright: 'Hak cipta dilindungi.',
    homeTitle: 'clicknclipcams — Penyewaan Kamera',
    homeMeta: 'clicknclipcams menyediakan jasa penyewaan kamera untuk mengabadikan momen, dengan pemesanan mudah dan kamera tepercaya.',
    heroVisual: 'Visual utama clicknclipcams',
    heroEyebrow: 'penyewaan kamera untuk keseharian',
    heroTitle: 'ABADIKAN MOMENMU.',
    heroSubtitle: 'Kamera terbaik untuk setiap momen kecil.',
    explore: 'JELAJAHI KAMERA',
    viewPrice: 'LIHAT HARGA',
    homeAboutEyebrow: 'tentang kami',
    homeTagline: 'Abadikan setiap momen bersama clicknclipcams.',
    homeDescription: 'clicknclipcams membantu Anda menyewa kamera dengan proses yang mudah, terjangkau, dan praktis untuk momen pribadi, konten, maupun kebutuhan dokumentasi sehari-hari.',
    homeValue1: 'Penyewaan kamera yang mudah',
    homeValue2: 'Harga transparan',
    homeValue3: 'Proses pemesanan cepat',
    homeValue4: 'Untuk momen yang tak ingin terlewat',
    homeCtaEyebrow: 'siap mengabadikan momen',
    homeCtaTitle: 'SIAP MENANGKAP MOMEN?',
    homeCtaDescription: 'Jelajahi pilihan kamera atau pesan langsung melalui WhatsApp.',
    homeCtaButton: 'PESAN SEKARANG ↗',
    camerasTitle: 'Kamera — clicknclipcams',
    camerasMeta: 'Lihat pilihan kamera clicknclipcams untuk disewa dan digunakan mengabadikan momen sehari-hari.',
    camerasEyebrow: 'pilih kamera untuk ceritamu',
    camerasHeading: 'PILIHAN KAMERA',
    cameraM100Description: 'Kamera tanpa cermin yang ringkas untuk foto santai, potret, dan cerita sehari-hari.',
    cameraM3Description: 'Kamera tanpa cermin serbaguna untuk perjalanan, gaya hidup, dan momen berkesan.',
    cameraJ5Description: 'Ringkas dan mudah digunakan untuk momen harian dan sesi foto kreatif.',
    cameraS2700Description: 'Kamera saku sederhana untuk perjalanan dan foto spontan.',
    startingFrom: 'Mulai dari',
    bookThis: 'PESAN KAMERA',
    cameraAltM100: 'Kamera Canon EOS M100',
    cameraAltM3: 'Kamera Canon EOS M3',
    cameraAltJ5: 'Kamera Nikon 1 J5',
    cameraAltS2700: 'Kamera Nikon Coolpix S2700',
    priceTitle: 'Daftar Harga — clicknclipcams',
    priceMeta: 'Informasi harga sewa kamera harian dan paket perlengkapan clicknclipcams.',
    priceEyebrow: 'harga sewa transparan',
    priceHeading: 'DAFTAR HARGA',
    tableCamera: 'Kamera',
    tablePrice: 'Harga',
    tableDuration: 'Durasi',
    day: '24 jam',
    additional: 'Biaya tambahan',
    extraBattery: '1 baterai: Rp20.000 / 24 jam',
    photoTransfer: 'Pemindahan foto: Rp15.000 / 200 foto',
    photoTransferNote: 'Pemindahan tetap dihitung Rp15.000 meskipun foto kurang dari 200.',
    included: 'Termasuk dalam paket',
    includedCamera: 'Unit kamera',
    includedCharger: 'Pengisi daya',
    includedMemory: 'Kartu memori / OTG',
    includedBag: 'Tas kamera',
    resultsTitle: 'Hasil Foto — clicknclipcams',
    resultsMeta: 'Lihat hasil foto dari kamera sewaan clicknclipcams.',
    resultsEyebrow: 'momen yang diabadikan',
    resultsHeading: 'HASIL FOTO clicknclipcams',
    galleryFilter: 'Filter galeri',
    filterAll: 'SEMUA',
    photoAltM100: 'Hasil foto dari Canon EOS M100',
    photoAltM3: 'Hasil foto dari Canon EOS M3',
    photoAltJ5: 'Hasil foto dari Nikon 1 J5',
    photoAltS2700: 'Hasil foto dari Nikon Coolpix S2700',
    lightboxAlt: 'Foto galeri diperbesar',
    closeLightbox: 'Tutup foto',
    previousImage: 'Foto sebelumnya',
    nextImage: 'Foto berikutnya',
    rulesTitle: 'Aturan Sewa — clicknclipcams',
    rulesMeta: 'Baca ketentuan sewa kamera clicknclipcams sebelum melakukan pemesanan.',
    rulesEyebrow: 'ketentuan penyewaan',
    rulesHeading: 'ATURAN SEWA',
    ruleRenterTitle: 'Persyaratan Penyewa',
    ruleRenterText: 'Penyewa wajib mengisi formulir sewa dan menyerahkan KTP asli. Untuk pengiriman, penyewa juga wajib mengirim foto swafoto sambil memegang KTP.',
    rulePaymentTitle: 'Pembayaran',
    rulePaymentText: 'Uang muka 50% dibayarkan untuk mengunci jadwal setelah formulir diisi. Pelunasan dilakukan sehari sebelum hari sewa. Pembayaran hanya nontunai.',
    ruleDeliveryTitle: 'Pengiriman & Pengembalian',
    ruleDeliveryText: 'Titik penjemputan atau pengiriman berada di Babelan, Bekasi. Biaya pengiriman ditanggung penyewa. Jadwal penjemputan pukul 06.00, 16.00, atau 21.00. Perubahan jam penjemputan tidak mengubah jam pengembalian yang mengikuti waktu pada formulir.',
    ruleDocumentationTitle: 'Dokumentasi Kondisi',
    ruleDocumentationText: 'Foto dan video kondisi barang wajib dibuat saat barang diterima. Jika tidak dilakukan, kerusakan selama masa sewa bukan tanggung jawab kami.',
    ruleDamageTitle: 'Kerusakan & Kehilangan',
    ruleDamageText: 'Penyewa bertanggung jawab atas kerusakan atau kehilangan dan wajib mengganti sesuai harga pasar. Kehilangan berkas akibat kesalahan memformat kartu memori juga menjadi tanggung jawab penyewa.',
    ruleLateTitle: 'Keterlambatan',
    ruleLateText: 'Denda keterlambatan Rp10.000 per jam. Keterlambatan lebih dari 12 jam dihitung sebagai tambahan sewa satu hari.',
    ruleCancelTitle: 'Pembatalan & Perubahan Tanggal',
    ruleCancelText: 'Pembatalan sepihak sebelum hari sewa menyebabkan uang muka hangus. Penjadwalan ulang hanya dapat dilakukan satu kali, paling lambat tiga hari sebelum sewa, dan bergantung pada ketersediaan jadwal.',
    ruleCareTitle: 'Perawatan & Larangan',
    ruleCareText: 'Jaga barang dengan baik, jangan pinjamkan tanpa izin, dan kembalikan seluruh perlengkapan dalam kondisi baik. Baterai harus dikembalikan dalam keadaan terisi penuh.',
    aboutTitle: 'Tentang — clicknclipcams',
    aboutMeta: 'Kenali clicknclipcams, layanan penyewaan kamera yang memudahkan siapa saja mengabadikan momen.',
    aboutEyebrow: 'cerita kami',
    aboutHeading: 'TENTANG clicknclipcams',
    aboutTagline: 'Abadikan setiap momen bersama clicknclipcams.',
    aboutDescription: 'clicknclipcams membuat fotografi lebih mudah dan terjangkau. Untuk jalan-jalan, sesi membuat konten, atau menyimpan kenangan, kami membantu Anda menyewa kamera yang sesuai tanpa proses pemesanan yang rumit.',
    aboutValue1: 'Penyewaan kamera terjangkau',
    aboutValue2: 'Proses pemesanan yang ramah',
    aboutValue3: 'Pengalaman yang berfokus pada fotografi',
    aboutValue4: 'Penjemputan dan pengiriman praktis',
    contactTitle: 'Kontak — clicknclipcams',
    contactMeta: 'Hubungi clicknclipcams untuk memesan kamera, mengecek ketersediaan, dan mengajukan pertanyaan.',
    contactEyebrow: 'hubungi kami',
    contactHeading: 'KONTAK',
    contactLabel: 'kontak',
    contactLead: 'Butuh kamera untuk momen berikutnya?',
    contactWhatsapp: 'Pesan melalui WhatsApp',
    contactFormTitle: 'Pesan kamera',
    namePlaceholder: 'Nama Anda',
    phonePlaceholder: 'Nomor telepon',
    cameraPlaceholder: 'Kamera yang diminati',
    shootPlaceholder: 'Ceritakan kebutuhan foto Anda',
    submitWhatsapp: 'PESAN VIA WHATSAPP',
    socialInstagram: 'Instagram clicknclipcams',
    socialWhatsapp: 'WhatsApp clicknclipcams',
    socialTiktok: 'TikTok clicknclipcams'
  },
  en: {
    navLabel: 'Main navigation',
    navHome: 'HOME',
    navCameras: 'CAMERAS',
    navPrice: 'PRICE',
    navResults: 'RESULTS',
    navRules: 'RULES',
    navAbout: 'ABOUT',
    navContact: 'CONTACT',
    brandHome: 'clicknclipcams home',
    languageLabel: 'Language selector',
    languageIndonesian: 'Bahasa Indonesia',
    languageEnglish: 'English',
    booking: 'BOOK NOW ↗',
    menuOpen: 'Open menu',
    menuClose: 'Close menu',
    copyright: 'All rights reserved.',
    homeTitle: 'clicknclipcams — Camera Rental',
    homeMeta: 'clicknclipcams offers camera rentals for memorable moments, with easy booking and trusted cameras.',
    heroVisual: 'clicknclipcams featured visual',
    heroEyebrow: 'camera rental for everyday moments',
    heroTitle: 'CAPTURE YOUR MOMENTS.',
    heroSubtitle: 'The right camera for every little moment.',
    explore: 'EXPLORE CAMERAS',
    viewPrice: 'VIEW PRICES',
    homeAboutEyebrow: 'about us',
    homeTagline: 'Capture every moment with clicknclipcams.',
    homeDescription: 'clicknclipcams makes camera rental easy, affordable, and convenient for personal moments, content creation, and everyday documentation.',
    homeValue1: 'Easy camera rental',
    homeValue2: 'Transparent pricing',
    homeValue3: 'Quick booking process',
    homeValue4: 'For moments worth keeping',
    homeCtaEyebrow: 'ready to capture',
    homeCtaTitle: 'READY TO CAPTURE?',
    homeCtaDescription: 'Explore the camera collection or book directly via WhatsApp.',
    homeCtaButton: 'BOOK NOW ↗',
    camerasTitle: 'Cameras — clicknclipcams',
    camerasMeta: 'Browse camera rentals from clicknclipcams for everyday moments and photography experiences.',
    camerasEyebrow: 'find a camera for your story',
    camerasHeading: 'OUR CAMERAS',
    cameraM100Description: 'Compact mirrorless camera for casual photos, portraits, and everyday stories.',
    cameraM3Description: 'Versatile mirrorless camera for travel, lifestyle, and memorable moments.',
    cameraJ5Description: 'Compact and easy to use for everyday moments and creative photo sessions.',
    cameraS2700Description: 'Simple point-and-shoot camera for travel and spontaneous photos.',
    startingFrom: 'Starting at',
    bookThis: 'BOOK THIS CAMERA',
    cameraAltM100: 'Canon EOS M100 camera',
    cameraAltM3: 'Canon EOS M3 camera',
    cameraAltJ5: 'Nikon 1 J5 camera',
    cameraAltS2700: 'Nikon Coolpix S2700 camera',
    priceTitle: 'Price List — clicknclipcams',
    priceMeta: 'Daily camera rental rates and included equipment from clicknclipcams.',
    priceEyebrow: 'clear rental pricing',
    priceHeading: 'PRICE LIST',
    tableCamera: 'Camera',
    tablePrice: 'Price',
    tableDuration: 'Duration',
    day: '24 hours',
    additional: 'Additional fees',
    extraBattery: '1 battery: Rp20,000 / 24 hours',
    photoTransfer: 'Photo transfer: Rp15,000 / 200 photos',
    photoTransferNote: 'The Rp15,000 fee still applies when transferring fewer than 200 photos.',
    included: 'Included in the rental',
    includedCamera: 'Camera body',
    includedCharger: 'Charger',
    includedMemory: 'Memory card / OTG',
    includedBag: 'Camera bag',
    resultsTitle: 'Photo Results — clicknclipcams',
    resultsMeta: 'View photos captured with clicknclipcams rental cameras.',
    resultsEyebrow: 'moments captured',
    resultsHeading: 'PHOTOS BY clicknclipcams',
    galleryFilter: 'Gallery filter',
    filterAll: 'ALL',
    photoAltM100: 'Photo taken with Canon EOS M100',
    photoAltM3: 'Photo taken with Canon EOS M3',
    photoAltJ5: 'Photo taken with Nikon 1 J5',
    photoAltS2700: 'Photo taken with Nikon Coolpix S2700',
    lightboxAlt: 'Expanded gallery photo',
    closeLightbox: 'Close photo',
    previousImage: 'Previous photo',
    nextImage: 'Next photo',
    rulesTitle: 'Rental Rules — clicknclipcams',
    rulesMeta: 'Read clicknclipcams rental terms before making a booking.',
    rulesEyebrow: 'rental terms',
    rulesHeading: 'RENTAL RULES',
    ruleRenterTitle: 'Renter Requirements',
    ruleRenterText: 'Renters must complete the rental form and provide their original Indonesian ID card (KTP). For delivery, renters must also send a selfie holding their KTP.',
    rulePaymentTitle: 'Payment',
    rulePaymentText: 'A 50% deposit secures the booking after the form is completed. The remaining balance is due one day before the rental. Cashless payment only.',
    ruleDeliveryTitle: 'Delivery & Return',
    ruleDeliveryText: 'Pickup and delivery are available in Babelan, Bekasi. Delivery fees are paid by the renter. Pickup times are 06:00, 16:00, or 21:00. A pickup-time change does not change the return time, which follows the time stated on the form.',
    ruleDocumentationTitle: 'Condition Check',
    ruleDocumentationText: 'Take photos and video of the equipment when you receive it. If you do not, we cannot be responsible for damage during the rental.',
    ruleDamageTitle: 'Damage & Loss',
    ruleDamageText: 'Renters are responsible for damage or loss and must reimburse the current market value. File loss caused by incorrectly formatting the memory card is also the renter’s responsibility.',
    ruleLateTitle: 'Late Returns',
    ruleLateText: 'Late returns incur a Rp10,000 fee per hour. A delay of more than 12 hours is charged as one additional rental day.',
    ruleCancelTitle: 'Cancellation & Rescheduling',
    ruleCancelText: 'A unilateral cancellation before the rental date forfeits the deposit. Rescheduling is allowed once, at least three days before the rental, subject to availability.',
    ruleCareTitle: 'Care & Restrictions',
    ruleCareText: 'Handle the equipment carefully, do not lend it without permission, and return every item in good condition. Batteries must be returned fully charged.',
    aboutTitle: 'About — clicknclipcams',
    aboutMeta: 'Meet clicknclipcams, a camera rental service that makes capturing moments easier for everyone.',
    aboutEyebrow: 'our story',
    aboutHeading: 'ABOUT clicknclipcams',
    aboutTagline: 'Capture every moment with clicknclipcams.',
    aboutDescription: 'clicknclipcams makes photography easy and affordable. Whether it is a day out, a content session, or a memory to keep, we help you rent a camera that fits without a complicated booking process.',
    aboutValue1: 'Affordable camera rental',
    aboutValue2: 'A friendly booking process',
    aboutValue3: 'A photography-first experience',
    aboutValue4: 'Convenient pickup and delivery',
    contactTitle: 'Contact — clicknclipcams',
    contactMeta: 'Contact clicknclipcams for camera bookings, availability, and questions.',
    contactEyebrow: 'get in touch',
    contactHeading: 'CONTACT',
    contactLabel: 'contact',
    contactLead: 'Need a camera for your next moment?',
    contactWhatsapp: 'Book via WhatsApp',
    contactFormTitle: 'Book a camera',
    namePlaceholder: 'Your name',
    phonePlaceholder: 'Phone number',
    cameraPlaceholder: 'Camera of interest',
    shootPlaceholder: 'Tell us about your photo plans',
    submitWhatsapp: 'BOOK VIA WHATSAPP',
    socialInstagram: 'Instagram clicknclipcams',
    socialWhatsapp: 'WhatsApp clicknclipcams',
    socialTiktok: 'TikTok clicknclipcams'
  }
};

const languageStorageKey = 'clicknclipcams-lang';
const getStoredLang = () => localStorage.getItem(languageStorageKey) || 'id';
window.getTranslation = (key, lang = getStoredLang()) => translations[lang]?.[key] || translations.id[key] || key;

function applyTranslations(lang = getStoredLang()) {
  const dictionary = translations[lang] || translations.id;

  document.querySelectorAll('[data-i18n]').forEach((node) => {
    const value = dictionary[node.dataset.i18n];
    if (value !== undefined) node.textContent = value;
  });

  const attributeMap = {
    'data-i18n-alt': 'alt',
    'data-i18n-aria': 'aria-label',
    'data-i18n-placeholder': 'placeholder',
    'data-i18n-title': 'title',
    'data-i18n-content': 'content'
  };

  Object.entries(attributeMap).forEach(([dataAttribute, attribute]) => {
    document.querySelectorAll(`[${dataAttribute}]`).forEach((node) => {
      const value = dictionary[node.getAttribute(dataAttribute)];
      if (value !== undefined) node.setAttribute(attribute, value);
    });
  });

  document.querySelectorAll('.lang-btn').forEach((button) => {
    const isActive = button.dataset.lang === lang;
    button.classList.toggle('active', isActive);
    button.setAttribute('aria-pressed', String(isActive));
  });

  document.documentElement.lang = lang;
}

function setLanguage(lang) {
  if (!translations[lang]) return;
  localStorage.setItem(languageStorageKey, lang);
  applyTranslations(lang);
  window.dispatchEvent(new CustomEvent('langChanged', { detail: { lang } }));
}

document.addEventListener('DOMContentLoaded', () => {
  applyTranslations(getStoredLang());

  document.querySelectorAll('.lang-btn').forEach((button) => {
    button.addEventListener('click', () => setLanguage(button.dataset.lang));
  });
});
